# Generated by Django 2.0.4 on 2018-05-16 18:58

from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('number_like', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#37474F', max_length=30)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('tab_home', models.CharField(default='tab1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('number_like', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'CommentsFilter',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to=journal.models.PathAndRename('images/2018/05/16'))),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('link', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('google', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('small_title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(default='null')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('view_number', models.IntegerField(default=0)),
                ('resume', models.TextField(blank=True, null=True)),
                ('comment_enable', models.BooleanField(default=True)),
                ('share_enable', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignalAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cause', models.TextField()),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cause', models.TextField()),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.TextField(default='#37474F', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ImageNews',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.Image')),
            ],
            bases=('journal.image',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.News')),
                ('video_url', models.URLField()),
                ('data_merge', models.IntegerField(default=2)),
                ('team_selection', models.BooleanField(default=False)),
            ],
            bases=('journal.news',),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Category'),
        ),
        migrations.AddField(
            model_name='news',
            name='journalist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Journalist'),
        ),
        migrations.AddField(
            model_name='news',
            name='primary_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Image'),
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(to='journal.Tag'),
        ),
        migrations.AddField(
            model_name='journalist',
            name='profile_picture',
            field=models.ForeignKey(default=60, on_delete=models.SET(60), to='journal.Image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.News'),
        ),
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Comment'),
        ),
        migrations.AddField(
            model_name='imagenews',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.News'),
        ),
    ]