# Generated by Django 2.0.4 on 2018-05-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20180517_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='displayed_text',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
