# Generated by Django 2.0.4 on 2018-05-19 23:43

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20180517_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=journal.models.PathAndRename('images/2018/05/19')),
        ),
    ]