# Generated by Django 2.0.4 on 2018-05-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20180519_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]