# Generated by Django 2.0.4 on 2018-05-25 16:47

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20180524_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='date_send',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=journal.models.PathAndRename('images/2018/05/25')),
        ),
        migrations.AlterField(
            model_name='news',
            name='comment_enable',
            field=models.BooleanField(default=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='news',
            name='share_enable',
            field=models.BooleanField(default=True, verbose_name='share'),
        ),
    ]
