# Generated by Django 2.0.4 on 2018-05-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20180527_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenews',
            options={'verbose_name_plural': 'Articles Images'},
        ),
        migrations.AddField(
            model_name='joinmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
