from django.contrib import admin
from .models import *


admin.site.register(Profile)
admin.site.register(Address)
admin.site.register(CommerceCategory)
admin.site.register(CommerceSCategory)
admin.site.register(Brand)
admin.site.register(Product)
admin.site.register(CommerceInformation)
admin.site.register(CommerceImage)
admin.site.register(CommerceRatting)
admin.site.register(Color)
admin.site.register(Specification)
admin.site.register(Sale)
admin.site.register(WishList)
admin.site.register(Cart)
admin.site.register(Order)
admin.site.register(OrderLine)
admin.site.register(Tag)
admin.site.register(Slide)
admin.site.register(Stock)
admin.site.register(ShippingAddress)
admin.site.register(BillingAddress)
admin.site.register(Mailing)
admin.site.register(Message)
admin.site.register(Description)
admin.site.register(Compare)
